name: flutter_template
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+29

environment:
  sdk: ">=3.0.6 <4.0.0"

scripts:
  generate:
    all: ./scripts/generate-all.sh
    translations: ./scripts/generate-translations.sh
  build_runner: flutter pub run build_runner build --delete-conflicting-outputs
  launch:
    dev: flutter run --flavor dev --dart-define=flavor=dev
    qa: flutter run --flavor qa --dart-define=flavor=qa
    prod: flutter run --flavor prod --dart-define=flavor=prod
  test:
    all: flutter test
    exclude-goldens: flutter test --exclude-tags=golden
    goldens: flutter test --tags=golden test/presentation/goldens
    update-goldens: flutter test --tags=golden test/presentation/goldens --update-goldens
    e2e: patrol test --flavor=qa --dart-define=flavor=qa
  analyze: flutter analyze --fatal-infos --fatal-warnings
  format: dart format --set-exit-if-changed lib
  fix: dart fix --apply
  build:
    apk:
      dev: flutter build apk --flavor=dev --dart-define=flavor=dev --debug
      qa: flutter build apk --flavor=qa --dart-define=flavor=qa --debug
      prod: flutter build apk --flavor=prod --dart-define=flavor=prod --debug
    release-apk:
      qa: flutter build apk --flavor=qa --dart-define=flavor=qa --release --obfuscate --split-debug-info=debug-info
      prod: flutter build apk --flavor=prod --dart-define=flavor=prod --release --obfuscate --split-debug-info=debug-info
    appbundle:
      dev: flutter build appbundle --flavor=dev --dart-define=flavor=dev
      qa: flutter build appbundle --flavor=qa --dart-define=flavor=qa
      prod: flutter build appbundle --flavor=prod --dart-define=flavor=prod
    ios:
      dev: flutter build ios --flavor=dev --dart-define=flavor=dev --debug --no-codesign
      qa: flutter build ios --flavor=qa --dart-define=flavor=qa --debug --no-codesign
      prod: flutter build ios --flavor=prod --dart-define=flavor=prod --debug --no-codesign
    web:
      dev: flutter build web --dart-define=flavor=dev
      qa: flutter build web --dart-define=flavor=qa
      prod: flutter build web --dart-define=flavor=prod


dependencies:
  auto_route: ^8.0.3
  collection: ^1.17.1
  cupertino_icons: ^1.0.5
  dio: ^5.0.3
  drift: ^2.5.0
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_hooks: ^0.20.0
  flutter_riverpod: ^2.3.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_state_notifier: ^1.0.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  hooks_riverpod: ^2.3.2
  json_annotation: ^4.8.1
  json_serializable: ^6.6.1
  logger: ^2.0.1
  path: ^1.8.2
  rxdart: ^0.27.7
  shared_preferences: ^2.0.18
  shimmer: ^3.0.0
  sqlite3_flutter_libs: ^0.5.20
  tuple: ^2.0.1
  uuid: ^4.3.3
  google_fonts: ^6.2.1
  easy_logger: ^0.0.2
  path_provider: ^2.0.13
  dynamic_color: ^1.6.6
  faker: ^2.1.0
  cached_network_image: ^3.2.3
  flutter_dotenv: ^5.0.2
  equatable: ^2.0.5

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.3.3
  drift_dev: ^2.5.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  golden_toolkit: ^0.15.0
  meta: ^1.11.0
  mocktail: ^1.0.3
  mason: ^0.1.0-dev.47
  patrol: ^3.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/pre_populated_cities.sqlite
    - assets/google_fonts/
    - .env
    - .env.dev
    - .env.qa
    - .env.test

patrol:
  app_name: flutter_template
  android:
    package_name: com.wednesday.flutter_template.qa
  ios:
    bundle_id: com.wednesday.flutterTemplate.qa