name: presentation
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^4.0.1
  collection: ^1.16.0
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  flutter_displaymode: ^0.4.0
  flutter_hooks: ^0.18.4
  flutter_riverpod: ^1.0.4
  flutter_staggered_grid_view: ^0.6.1
  flutter_state_notifier: ^0.7.1
  freezed_annotation: ^2.0.3
  hooks_riverpod: ^1.0.4
  intl: ^0.17.0
  logger: ^1.1.0
  shimmer: ^2.0.0
  tuple: ^2.0.0
  google_fonts: ^2.3.2
  easy_logger: ^0.0.2
  dynamic_color: ^1.2.2
  cached_network_image: ^3.2.0

  presentation_entity:
    path: ../presentation_entity

  foundation:
    path: ../foundation

  interactor:
    path: ../interactor

  get_it: ^7.2.0
  easy_localization: ^3.0.1
  rxdart: ^0.27.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.10
  freezed: ^2.0.3+1
  golden_toolkit: ^0.13.0
  meta: ^1.7.0
  mocktail: ^0.3.0
  base_test:
    path: ../base_test

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
